

title: "Standards Not Force"
url: "https://standardsnotforce.org"
baseurl: ""

tagline: Standards, Not Force is a lawful, nonviolent civic standards initiative that protects families and stabilizes communities through education and transparency.
description: "Standards, Not Force: How We Hold Institutions Accountable Without Violence This address examines how institutions can be held accountable without violence or escalation. I discuss why chaos fails, what history teaches about durable civic pressure, and how disciplined, coordinated action protects communities while influencing institutional change"

# Author / Social (Used for Twitter Cards/Open Graph)
author:
  name: "Standards Not Force"
  # twitter: "your_handle" # Optional


social:
  name: Standards Not Force
  links:
    - https://substack.com/@standardsnotforce
    - https://www.youtube.com/@FORMERBLACKPANTHERSPEAKS
    - https://www.reddit.com/r/StandardsNotForce
    - https://bsky.app/profile/standardsnotforce.bsky.social


markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Analytics (PostHog)
# This makes it easy to swap IDs without hunting through HTML files

posthog:
  tracking_id: phc_UjmS6WA0gYTWKOjcpwJVMXQ5MXBaB5wUsZwhZ7FZlMV


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - .jekyll-cache/
  - README.md